### ISSUE TITLE
Error: (HTTP code 404) no such container - No such image: statusteam/nim-waku:v0.17.0 

### ISSUE THREAD

**Issue by fryorcraken** [waku-org/js-waku#1372]
This is a **bug report**

## Problem

Can't run the tests

```
  waku:docker Confirming that image statusteam/nim-waku:v0.17.0 exists +0ms
  waku:docker Image statusteam/nim-waku:v0.17.0 successfully found +0ms
  waku:docker Args: --listen-address=0.0.0.0 --rpc=true --relay=true --rpc-admin=true --websocket-support=true --log-level=TRACE --rpc-port=32034 --tcp-port=32035 --websocket-port=32036 --rpc-address=0.0.0.0 --store=false --filter=false --lightpush=false +0ms
  waku:docker 
Error: (HTTP code 404) no such container - No such image: statusteam/nim-waku:v0.17.0 
    at /home/fryorcraken/src/waku-org/js-waku/node_modules/docker-modem/lib/modem.js:343:17
    at getCause (/home/fryorcraken/src/waku-org/js-waku/node_modules/docker-modem/lib/modem.js:373:7)
    at Modem.buildPayload (/home/fryorcraken/src/waku-org/js-waku/node_modules/docker-modem/lib/modem.js:342:5)
    at IncomingMessage.<anonymous> (/home/fryorcraken/src/waku-org/js-waku/node_modules/docker-modem/lib/modem.js:310:16)
    at IncomingMessage.emit (node:events:525:35)
    at IncomingMessage.emit (node:domain:489:12)
    at endReadableNT (node:internal/streams/readable:1359:12)
    at processTicksAndRejections (node:internal/process/task_queues:82:21)
```

Note that the nwaku v0.17.0 image is **not** available locally:

```
▶ docker image ls
REPOSITORY            TAG       IMAGE ID       CREATED         SIZE
statusteam/nim-waku   v0.16.0   6552ce43adc7   2 months ago    89.7MB
hello-world           latest    feb5d9fea6a5   20 months ago   13.3kB
```

## Proposed Solutions

Looks like it's not waiting for the docker pull properly.

## Notes

I was able to manually pull the image:

```
▶ docker pull statusteam/nim-waku:v0.17.0
v0.17.0: Pulling from statusteam/nim-waku
91d30c5bc195: Pull complete 
af00591544c8: Pull complete 
fc57fd0a76d0: Pull complete 
0be7233eadbb: Pull complete 
1de604c62e94: Pull complete 
ff12f1350730: Pull complete 
Digest: sha256:1a898d4a45d599f68e5c2b027960c391d226f28c51585d8f8378b74ce0d5eaaa
Status: Downloaded newer image for statusteam/nim-waku:v0.17.0
docker.io/statusteam/nim-waku:v0.17.0
```

So there must be an issue with the script.

commit c8c2cbfbb199b799b7ff4203e643b30a154b7775

**Comment by fryorcraken** [comment]
Cc @danisharora099

**Comment by fryorcraken** [comment]
Also noticed some odd logging:

```
  waku:node Waiting to see 'Node setup complete' in type() {
  waku:node         return isGoWaku ? "go-waku" : "nwaku";
  waku:node     } logs +947ms
  waku:node type() {
  waku:node         return isGoWaku ? "go-waku" : "nwaku";
  waku:node     } node has been started +102ms
```

**Comment by fryorcraken** [comment]
Did #1375 fix it? Logging is weird because it says "found 0.17.0" when it was clearly not "found".,
