### ISSUE TITLE
investigate stream creation error

### ISSUE THREAD

**Issue by danisharora099** [waku-org/js-waku#1563]
This is a support request

## Problem

With the upgrade of `web-chat` example to the new release of js-waku that introduces `StreamManager`, an error is seen randomly:
```
stream_manager.js:38 Uncaught (in promise) Error: Failed to get a connection to the peer
    at StreamManager.newStream (stream_manager.js:38:1)
    at StreamManager.prepareNewStream (stream_manager.js:43:1)
    at StreamManager.getStream (stream_manager.js:26:1)
    at WakuPeerExchange.getStream (base_protocol.js:22:1)
    at WakuPeerExchange.query (waku_peer_exchange.js:33:1)
    at async PeerExchangeDiscovery.query (waku_peer_exchange_discovery.js:85:1)
```

## Proposed Solutions

Yet to investigate

## Notes

- not a breaking change

**Comment by fryorcraken** [comment]
Closed in favour of #1569
