### ISSUE TITLE
chore: make Karma working locally 

### ISSUE THREAD

**Issue by weboko** [waku-org/js-waku#1707]
This is a **support request**

## Problem

On Mac OS Sonoma (event on prev versions) `npm run test` in `js-waku` root does not work as expected with failing:
```bash
UnhandledRejection: Error: ENOENT: no such file or directory, open '/var/folders/qh/kx7m505d35l2_wtqnq_bqrwc0000gn/T/_karma_webpack_677678/../../../../../../Users/okozlov/Status/js-waku/packages/dns-discovery/dist/dns.d.ts'
    at Object.openSync (node:fs:601:3)
    at Object.readFileSync (node:fs:469:35)
    at /Users/okozlov/Status/js-waku/node_modules/karma-webpack/lib/webpack/plugin.js:20:66
    at Array.forEach (<anonymous>)
    at /Users/okozlov/Status/js-waku/node_modules/karma-webpack/lib/webpack/plugin.js:16:29
    at Hook.eval [as callAsync] (eval at create (/Users/okozlov/Status/js-waku/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:9:1)
    at Hook.CALL_ASYNC_DELEGATE [as _callAsync] (/Users/okozlov/Status/js-waku/node_modules/tapable/lib/Hook.js:18:14)
    at /Users/okozlov/Status/js-waku/node_modules/webpack/lib/Compiler.js:498:23
    at Compiler.emitRecords (/Users/okozlov/Status/js-waku/node_modules/webpack/lib/Compiler.js:919:5)
    at /Users/okozlov/Status/js-waku/node_modules/webpack/lib/Compiler.js:490:11
```

## Proposed Solutions

To investigate it and figure out how to make it run on:
- [ ] Windows;
- [ ] Mac;
- [ ] Linux?;

**Comment by weboko** [comment]
@fryorcraken it seems your local setup was working? 
@danisharora099 does it work locally for you?

**Comment by weboko** [comment]
Happens to me and @adklempner. Tried to run on a clean but no luck.

**Comment by adklempner** [comment]
I was able to get karma working locally. I tried all sorts of approaches (changing the karma config, changing the webpack config) but finally what worked is switching from the latest published npm version of `karma-webpack` to the latest commit: https://github.com/codymikol/karma-webpack/commit/2337a82beb078c0d8e25ae8333a06249b8e72828

The repository had recently switched maintainers and a new npm package has not been published since Feb 2021.

I still get the following errors for two of the tests but it seems to be a separate issue:
```
ERROR in /Users/arseniy/Waku/js-waku/packages/dns-discovery/src/dns.spec.ts
./src/dns.spec.ts 5:39-62
[tsl] ERROR in /Users/arseniy/Waku/js-waku/packages/dns-discovery/src/dns.spec.ts(5,40)
      TS2821: Import assertions are only supported when the '--module' option is set to 'esnext' or 'nodenext'.
ts-loader-default_e3b0c44298fc1c14

ERROR in /Users/arseniy/Waku/js-waku/packages/dns-discovery/src/enrtree.spec.ts
./src/enrtree.spec.ts 4:39-62
[tsl] ERROR in /Users/arseniy/Waku/js-waku/packages/dns-discovery/src/enrtree.spec.ts(4,40)
      TS2821: Import assertions are only supported when the '--module' option is set to 'esnext' or 'nodenext'.
ts-loader-default_e3b0c44298fc1c14
```
