### ISSUE TITLE
bug: connections closes after ~30 messages sent via lightpush

### ISSUE THREAD

**Issue by fbarbu15** [waku-org/js-waku#1790]
This is a **bug report**

## Steps
1. Have jswaku and nwaku(or gowaku) connected via filter and lightpush protocols
2. Subscribe jswaku to a topic
3. Send 100 messages from jswaku via lightpush

## Results
After ~30 messages the connections closes
```
  waku:error:stream-manager:/vac/waku/lightpush/2.0.0-beta1 Failed to prepare a new stream for 16Uiu2HAkvsoBeWj3NwGqZ4R1mmSQQzqmRwpCdmgYLmrMts7HZ9ne +0ms
  waku:error:stream-manager:/vac/waku/lightpush/2.0.0-beta1 Failed to prepare a new stream for 16Uiu2HAkvsoBeWj3NwGqZ4R1mmSQQzqmRwpCdmgYLmrMts7HZ9ne +0ms
  waku:error:light-push Failed to get a stream for remote peer16Uiu2HAkvsoBeWj3NwGqZ4R1mmSQQzqmRwpCdmgYLmrMts7HZ9ne CodeError: the connection is being closed
    at ConnectionImpl.newStream (file:///home/fbarbu15/WORK_DIR/js-waku/node_modules/libp2p/src/connection/index.ts:119:13)
    at StreamManager.newStream (file:///home/fbarbu15/WORK_DIR/js-waku/packages/core/src/lib/stream_manager.ts:54:23)
    at StreamManager.getStream (file:///home/fbarbu15/WORK_DIR/js-waku/packages/core/src/lib/stream_manager.ts:42:19)
    at async file:///home/fbarbu15/WORK_DIR/js-waku/packages/core/src/lib/light_push/index.ts:127:18
    at async Promise.allSettled (index 0)
    at async LightPush.send (file:///home/fbarbu15/WORK_DIR/js-waku/packages/core/src/lib/light_push/index.ts:179:21)
    at async Context.<anonymous> (file:///home/fbarbu15/WORK_DIR/js-waku/packages/tests/tests/filter/subscribe.node.spec.ts:174:13) {
  code: 'ERR_CONNECTION_BEING_CLOSED',
  props: {}
```

Attached test logs and nwaku docker log
[js_waku_log.log](https://github.com/waku-org/js-waku/files/13939197/js_waku_log.log)
[wakunode_Waku_Filter_V2_Subscribe_Subscribe_to_100_topics_at_once_and_receives_messages.log](https://github.com/waku-org/js-waku/files/13939198/wakunode_Waku_Filter_V2_Subscribe_Subscribe_to_100_topics_at_once_and_receives_messages.log)

- js-waku version: master
- Environment: node js
- Nodes connected to too: nwaku or go-waku latest

**Comment by danisharora099** [comment]
Thanks for flagging this @fbarbu15, we'll investigate this on our end. 

Thanks!

**Comment by fbarbu15** [comment]
This test reproduces the bug: https://github.com/waku-org/js-waku/pull/1791/files#diff-1c6dd30f4229c376d4619ed981a247180ae4c69a9582292dd03899196eac8b84R224
It's on this branch` chore/max-sub-topic-count`
They are awaited:
```
topicCount = 100
for (let i = 0; i < topicCount; i++) {
      await waku.lightPush.send(td.encoders[i], {
        payload: utf8ToBytes(`Message for Topic ${i + 1}`)
      });
    }
```

**Comment by danisharora099** [comment]
@fbarbu15 this seems to be resolved with https://github.com/waku-org/js-waku/pull/1791
Is that correct?

Can we close this issue?
