### ISSUE TITLE
Using js-waku @next

### ISSUE THREAD

**Issue by vpavlin** [waku-org/js-waku#2112]
This is a **support request**

## Problem

I'm trying to update my `waku-dispatcher` library to use `@next` versions of the waku packages to leverage the reliability work + TWN, but I am hitting some issues - not saying they are caused by js-waku, but I would appreciate some help debugging/resolving them

* I see `AbortError` messages for lightpush and filter
  ```
  waku:error:light-push Failed to send waku light push request +1ms 
  AbortError: Read aborted
    at AbortSignal.listener (￼index.ts:119:1)
    at AbortSignal.onAbort (￼index.ts:14:1)
   ```
   ```
   waku:error:filter:v2 Error with receiving pipe +4ms
   AbortError: Read aborted
    at AbortSignal.listener (index.ts:119:1)
    at AbortSignal.onAbort (index.ts:14:1)
   ```
* I see a big churn of nodes - constant disconnections and reconnections - even from my own nwaku node, which causes Filter to be unusable, since the subscription is rarely actually connected
* I can rarely publish a message - getting `No stream available` or `Generic error` most of the time
* Even if I disable `defaultBootstrap` and try to only rely on my own node, the situation is basically the same 

The main goal of this issue is to figure out if there is explicit cause of this behaviour

Code: https://github.com/vpavlin/waku-dispatcher/blob/chore/update-js-waku/src/index.ts#L32

**Comment by weboko** [comment]
What you see most likely is because nodes your are connected to are not TWN nodes and thus they are just getting dropped due to being incompatible with js-waku as you are using `defaultBootstrap` too. 

Also, can you make sure you use similar version to https://github.com/waku-org/lab.waku.org/commit/179b501c2753bb3530ccd5be664f8effe6a48ee9 ?

**Comment by vpavlin** [comment]
I was trying to pin to a particular version, but had some dependency issues, so I used waku/sdk@next. Trying with `0.0.27-39f8920.0` - seems to be working better!

Will test a bit more and report back:) Why was it "broken" with `@next`? When/How is that updated?

**Comment by weboko** [comment]
I am not sure why it happens, last `@waku/sdk@next` is pointing to `0.0.27-39f8920.0`
https://www.npmjs.com/package/@waku/sdk?activeTab=versions

It can be due to cache or maybe you were installing it before I published working version.
