### ISSUE TITLE
Cannot push value onto an ended pushable

### ISSUE THREAD

**Issue by vpavlin** [waku-org/js-waku#2157]
This is a **bug repor**

## Problem

I am occassionally seeing following error when executing Store query

```
dispatcher.ts:493 Error: Cannot push value onto an ended pushable
    at QueuelessPushable._push (index.ts:134:1)
    at QueuelessPushable.push (index.ts:120:1)
    at duplex.sink (index.ts:95:1)
```

## Proposed Solutions

N/A

## Notes

- js-waku version     "@waku/sdk": "0.0.29-00c3261.0",

**Comment by weboko** [comment]
Todo for this task:
- do more dogfooding for Store;
- observe if following problem occurs;

**Comment by weboko** [comment]
Store is buggy and not possible to debug that case. For pushable streams it shouldn't happen anymore as we upgraded libp2p deps.
